name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          echo ${{ secrets.GCR_TOKEN }} | docker login -u _json_key --password-stdin https://gcr.io
        env:
          GCR_TOKEN: ${{ secrets.GCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/chatbot-gabi:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/chatbot-gabi:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy chatbot-gabi \
            --image=gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/chatbot-gabi:${{ github.sha }} \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated